name: Build Installer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_dlls:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration:
          - 'Release-2025'
          - 'Release-2024'
          - 'Release-2023'
          - 'Release-2022'
          - 'Release-2021'
          - 'Release-2020'
    env:
      Solution_Name: SchedulesExcelExport.sln
      Test_Project_Path: src/SchedulesExcelExport.csproj
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Build DLLs
      run: dotnet build --configuration ${{ matrix.configuration }}

    - name: Upload DLL Archive
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }}
        path: output/${{ matrix.configuration }}

  compile_installer:
    runs-on: windows-latest
    needs: build_dlls
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download DLL Archives
      uses: actions/download-artifact@v4
      with:
        path: ./output

    - name: List Output Directory
      shell: pwsh
      run: |
        Write-Host "Output Directory Structure:"
        Get-ChildItem -Recurse -Path './output' | Format-Table -Property FullName

    - name: Compile Inno Setup Script
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "InnoSetup\SchedulesExcelExport.iss"

    - name: Upload Compiled Installer
      uses: actions/upload-artifact@v4
      with:
        name: SchedulesExcelExport.Revit
        path: "./output/*.exe"
